### ISSUE TITLE
Make network_control v0.5.0 pip installable

### ISSUE THREAD

**Issue by JohannesWiesner** [BassettLab/control_package#20]
Hey Team Bassett,

we would like to install your newest version `v0.5.0`. Are you planning on making this pip installable? Or should this be considered as a dev version? Otherwise, I would git clone v.0.5.0

**Comment by jastiso** [comment]
It will be pip installable soon, there are a couple more things we want to add first though. Technically the whole package is still in beta, but I'd probably recommend working with a git clone of v0.5.0. We've added some parameters since v0.4.0 about specifying discrete or continuous time that will be important to put into your workflow :)

**Comment by JohannesWiesner** [comment]
Hi Jeni, thanks for the answer! Alright I will clone v0.5.0 then! :)
