### ISSUE TITLE
Why is identity matrix not subtracted in network_control.utils.matrix_normalization?

### ISSUE THREAD

**Issue by JohannesWiesner** [BassettLab/control_package#21]
We were wondering, why the identity matrix is not subtracted in [`network_control.utils.matrix_normalization`](https://github.com/BassettLab/control_package/blob/ce9d2a56bbcd2da99316c84db135b5af10d24188/src/network_control/utils.py#L34)? So far we were following the implementation as [e.g. described in this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7734595/). What is the rationale for not subtracting `I`?

**Comment by jk6294** [comment]
Hi @JohannesWiesner, 

Thank you for raising this issue! Looking at the code, the function matrix_normalization is:

`def matrix_normalization(A, version=None, c=1):
    '''

    Args:
        A: np.array (n_parcels, n_parcels)
            adjacency matrix from structural connectome
        version: str
            options: 'continuous' or 'discrete'. default=None
            string variable that determines whether A is normalized for a continuous-time system or a discrete-time
            system. If normalizing for a continuous-time system, the identity matrix is subtracted.
        c: int
            normalization constant, default=1
    Returns:
        A_norm: np.array (n_parcels, n_parcels)
            normalized adjacency matrix

    '''

    if version == 'continuous':
        print("Normalizing A for a continuous-time system")
    elif version == 'discrete':
        print("Normalizing A for a discrete-time system")
    elif version == None:
        raise Exception("Time system not specified. "
                        "Please nominate whether you are normalizing A for a continuous-time or a discrete-time system "
                        "(see function help).")

    # singluar value decomposition
    u, s, vt = svd(A)

    # Matrix normalization for discrete-time systems
    A_norm = A / (c + s[0])

    if version == 'continuous':
        # for continuous-time systems
        A_norm = A_norm - np.eye(A.shape[0])

    return A_norm`

The subtraction of I is reserved for continuous-time systems, whereas discrete-time systems do not require such subtraction. The reason why is because the goal of normalizing is to ensure that A is stable. What it means for A to be stable is different depending on whether the system is a continuous-time system or a discrete-time system.

In a continuous-time system (i.e. \dot{x} = Ax + Bu), the requirement is that the real component of all eigenvalues of A are negative. This is why we subtract I from A, because the subtraction shifts the real components of the eigenvalues of A to be negative.

In a discrete-time system (i.e. x(t+1) = Ax(t) + Bu(t)), the requirement is that the magnitude of all eigenvalues lie within the unit circle. This is why we do not need to subtract I from A.

I hope this answers your question!

**Comment by JohannesWiesner** [comment]
Hi @jk6294,

thanks for the answer and especially for the explanation! I guess I was just referring to `v0.4.0` where the subtraction of continuous time systems was not defined yet :) 

Greetings,

Johannes
