### ISSUE TITLE
Function get_control_inputs error with system='discrete' (index out of bounds)

### ISSUE THREAD

**Issue by neudorf** [BassettLab/control_package#34]
Hello and thank you for putting together this great toolbox! 

I just wanted to share an issue I am coming across when trying to run the `get_control_inputs` function with the system set to `'discrete'`. This is using the same method in the example at `https://nctpy.readthedocs.io/en/latest/pages/getting_started/index.html` but with system changed from `'continuous'` to `'discrete'`. The example worked when set to `system='continuous'`.

```
IndexError                                Traceback (most recent call last)
nctpy_analyses.py in line 20
     310 B = np.eye(n_nodes)
     312 # get the state trajectory (x) and the control inputs (u)
---> 313 x, u, n_err = get_control_inputs(A_norm=A_norm, T=T, B=B, x0=x0, xf=xf, system=system, rho=rho, S=S)

File ~/miniconda3/envs/nctpy/lib/python3.9/site-packages/nctpy/energies.py:205, in get_control_inputs(A_norm, T, B, x0, xf, system, xr, rho, S, expm_version)
    203         M[np.ix_(z + (i - 1) * n_nodes, z + (i - 1) * n_nodes)] = I
    204     if i != 0:
--> 205         M[np.ix_(z + (i - 0) * n_nodes, z + (i - 1) * n_nodes)] = -A_norm
    207 # Constraints for the costate equations
    208 for i in np.arange(1, T):

IndexError: index 5 is out of bounds for axis 0 with size 5
```

**Comment by jastiso** [comment]
Hi! Thanks for using the package and bringing this issue to our attention.

This is the expected behavior for a discrete system when T = 1. For discrete systems, you need at least 2 discrete time points for the system to evolve at all, so T has to be greater than or equal to 2. There is sort of an implicit assumption that time is 1 indexed and not 0 indexed. This error is also a common source of confusion, so I'm going to suggest we change the function to have a more informative error.
